version: '3.8'

services:
  traefik:
    image: traefik:v3.0
    container_name: clarityxdr-traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --api.dashboard=true
      - --api.insecure=true
    networks:
      - app-network
    labels:
      - "clarityxdr.service=proxy"
      - "clarityxdr.component=traefik"
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.${DOMAIN_NAME}`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth"
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=${TRAEFIK_DASHBOARD_AUTH}"

  postgres:
    image: postgres:15-alpine
    container_name: clarityxdr-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=en_US.UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app-network
    labels:
      - "clarityxdr.service=database"
      - "clarityxdr.component=postgres"

  pgbouncer:
    image: edoburu/pgbouncer:latest
    container_name: clarityxdr-pgbouncer
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      POOL_MODE: transaction
      MAX_CLIENT_CONN: 200
      DEFAULT_POOL_SIZE: 40
      RESERVE_POOL_SIZE: 20
      RESERVE_POOL_TIMEOUT: 5
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    labels:
      - "clarityxdr.service=database"
      - "clarityxdr.component=pgbouncer"

  redis:
    image: redis:7-alpine
    container_name: clarityxdr-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD} --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    labels:
      - "clarityxdr.service=cache"
      - "clarityxdr.component=redis"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    container_name: clarityxdr-backend
    restart: unless-stopped
    environment:
      - DB_HOST=pgbouncer
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - DB_SSL_MODE=require
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - NODE_ENV=production
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - KQL_TIMEOUT=${KQL_TIMEOUT:-60}
      - AGENT_QUERY_TIMEOUT=${AGENT_QUERY_TIMEOUT:-300}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-24h}
    volumes:
      - ./repositories:/app/repositories
      - ./uploads:/app/uploads
      - ./client-rules:/app/client-rules
    depends_on:
      postgres:
        condition: service_healthy
      pgbouncer:
        condition: service_started
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.${DOMAIN_NAME}`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.backend.loadbalancer.server.port=8080"
      - "clarityxdr.service=backend"
      - "clarityxdr.component=api"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
      args:
        - REACT_APP_API_URL=https://api.${DOMAIN_NAME}
    container_name: clarityxdr-frontend
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=https://api.${DOMAIN_NAME}
      - NODE_ENV=production
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      - "clarityxdr.service=frontend"
      - "clarityxdr.component=web"
    networks:
      - app-network

  agent-orchestrator:
    build:
      context: ./agent-orchestrator
      dockerfile: Dockerfile
    container_name: clarityxdr-agent-orchestrator
    restart: unless-stopped
    environment:
      - DB_HOST=pgbouncer
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "clarityxdr.service=ai"
      - "clarityxdr.component=orchestrator"
    networks:
      - app-network

  backup:
    image: postgres:15-alpine
    container_name: clarityxdr-backup
    restart: unless-stopped
    environment:
      PGPASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./backups:/backups
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      bash -c "
      while true; do
        echo 'Starting backup at $$(date)'
        pg_dump -h postgres -U ${POSTGRES_USER} -Fc ${POSTGRES_DB} > /backups/backup_$$(date +%Y%m%d_%H%M%S).dump
        find /backups -name '*.dump' -mtime +7 -delete
        echo 'Backup completed at $$(date)'
        sleep 86400
      done"
    networks:
      - app-network
    labels:
      - "clarityxdr.service=backup"
      - "clarityxdr.component=postgres"

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16